### ISSUE TITLE
Support for 64bit cpu architecture

### ISSUE THREAD

**Issue by daniaDlbani** [c0i/cocos2d-x226-android-studio#3]
I've downloaded the HelloWorld project, and follow the steps, I can run project in android studio with cocos 2.2.6 however the debug is not working at all. Also I'm using android-ndk-r13b. Android studio version 3.2.1

**Comment by yinjimmy** [comment]
did you set breakpoint and debug run ?

![image](https://user-images.githubusercontent.com/5056328/52545328-9b74c480-2df1-11e9-8c2a-288f591e8216.png)

**Comment by daniaDlbani** [comment]
sure I did but it skip all breakpoints, also build variant set to debug mode.

**Comment by daniaDlbani** [comment]
I find out that my device cpu architecture "arm64-v8a" wasn't supported in the app config, 
I've added it to gradle.properties `PROP_APP_ABI=armeabi-v7a:x86:arm64-v8a`
and to hello gradle file `abiFilters = ["armeabi-v7a", "arm64-v8a", "x86"]`.
However ndk build stopped giving an error that `NDK build error - $(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES  point to a missing file`

**Comment by yinjimmy** [comment]
need to update 3rd libs. plz ref to https://github.com/c0i/cocos2d-x-v2

**Comment by daniaDlbani** [comment]
thanks I will try them.

**Comment by daniaDlbani** [comment]
I've downloaded and replace the prebuilt folder , 
1. In  applicaiton.mk update APP_ABI := armeabi-v7a x86 arm64-v8a
2. In gradle.properties PROP_APP_ABI=armeabi-v7a:x86:arm64-v8a
3. In build.gradle abiFilters = ["armeabi-v7a", "arm64-v8a", "x86"]
clean and build but still getting NDK build error 
`$(LOCAL_MAKEFILE):$(LOCAL_MODULE): LOCAL_SRC_FILES point to a missing file
 ndk aborting build Check that $(prebuilt_path) exists, or that its path is correct`

**Comment by yinjimmy** [comment]
full compile log, plz,

you need to add libz to `cocos/android.mk`

```mk
LOCAL_WHOLE_STATIC_LIBRARIES := cocos_libzlib_static #############
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_libpng_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_jpeg_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_libxml2_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_libtiff_static
LOCAL_WHOLE_STATIC_LIBRARIES += cocos_libwebp_static

# define the macro to compile through support/zip_support/ioapi.c
LOCAL_CFLAGS := -Wno-psabi -DUSE_FILE32API
LOCAL_EXPORT_CFLAGS := -Wno-psabi -DUSE_FILE32API

include $(BUILD_STATIC_LIBRARY)

$(call import-module,libjpeg)
$(call import-module,libzlib)   ###################
$(call import-module,libpng)
```

or you can use some folder compare tools to merge file
or you can just replace the `cocos2dx` folder if you dont modify engine.

**Comment by daniaDlbani** [comment]
Android NDK: Check that /cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/arm64-v8a/libcurl.a exists  or that its path is correct

**Comment by yinjimmy** [comment]
https://github.com/c0i/cocos2d-x-v2/tree/v1.0-alpha support curl and websockets Android arm64 .

**Comment by yinjimmy** [comment]
add missing files https://github.com/c0i/cocos2d-x-v2/commit/8c5f8aaa8c8db40bac633c8e5b8d8bccddbfba47

**Comment by daniaDlbani** [comment]
Actually I'm still moving my cocos2dx 2.2.6 project from eclipse to Android studio. What I have now is just the hello world sample. I will test those changes when I'm done. Thank you for your efforts.

**Comment by yinjimmy** [comment]
1. test https://github.com/c0i/cocos2d-x-v2/tree/master/projects/hello
2. merge your project into `hello` project

**Comment by daniaDlbani** [comment]
I will do thank you.

**Comment by daniaDlbani** [comment]
I can't build the project here's the stack trace:

org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':hello'.
	at org.gradle.configuration.project.LifecycleProjectEvaluator.wrapException(LifecycleProjectEvaluator.java:79)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.addConfigurationFailure(LifecycleProjectEvaluator.java:73)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$400(LifecycleProjectEvaluator.java:54)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$EvaluateProject.run(LifecycleProjectEvaluator.java:110)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:68)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:687)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:140)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:41)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:274)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:182)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:141)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:124)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:77)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:74)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:154)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:38)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:96)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:74)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:55)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.run(RunAsBuildOperationBuildActionRunner.java:50)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:44)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:79)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:80)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:53)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:62)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:34)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:46)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:81)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:122)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:295)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.GradleException: executing external native build for ndkBuild /SiraPackage/TheSira/Projects/SiraAs/proj.android-studio/app/jni/Android.mk
	at com.android.build.gradle.internal.ExtraModelInfo.handleIssue(ExtraModelInfo.java:114)
	at com.android.builder.core.ErrorReporter.handleSyncError(ErrorReporter.java:80)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.build(ExternalNativeJsonGenerator.java:191)
	at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$7(BasePlugin.java:647)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:635)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1$1.run(DefaultListenerBuildOperationDecorator.java:155)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:58)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:152)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction.execute(DefaultListenerBuildOperationDecorator.java:149)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy29.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:187)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:184)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1418)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:193)
	... 95 more

**Comment by daniaDlbani** [comment]
Error Android NDK: ```
Check that
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcrypto.a exists  or that its path is correct   
```

**Comment by daniaDlbani** [comment]
Check that
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcrypto.a exists  or that its path is correct

**Comment by yinjimmy** [comment]
plz `git pull` and test again.

files ignore by git.

https://github.com/c0i/cocos2d-x-v2/commit/db0ab44742abd125264c801dce89816ee643fa7e

**Comment by daniaDlbani** [comment]
Build Error:
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogSetupDecode: error: undefined reference to 'inflateInit_'
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogPreDecode: error: undefined reference to 'inflateReset'
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogDecode: error: undefined reference to 'inflate'
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogDecode: error: undefined reference to 'inflateSync'
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogSetupEncode: error: undefined reference to 'deflateInit_'
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogPreEncode: error: undefined reference to 'deflateReset'
cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/x86/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogEncode: error: undefined reference to 'deflate'

**Comment by daniaDlbani** [comment]
/Cocos2dx-v2/extensions/CocoStudio/Json/CocoLoader.cpp:184: error: undefined reference to 'uncompress'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:149: error: undefined reference to 'inflateInit2_'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:154: error: undefined reference to 'inflate'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:191: error: undefined reference to 'inflateEnd'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:167: error: undefined reference to 'inflateEnd'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:180: error: undefined reference to 'inflateEnd'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:240: error: undefined reference to 'gzopen'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:258: error: undefined reference to 'gzread'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:294: error: undefined reference to 'gzclose'
Cocos2dx-v2/cocos2dx/support/zip_support/ZipUtils.cpp:401: error: undefined reference to 'uncompress'
Cocos2dx-v2/cocos2dx/support/zip_support/unzip.cpp:1618: error: undefined reference to 'inflateInit2_'
Cocos2dx-v2/cocos2dx/support/zip_support/unzip.cpp:1820: error: undefined reference to 'crc32'
Cocos2dx-v2/cocos2dx/support/zip_support/unzip.cpp:1888: error: undefined reference to 'inflate'
Cocos2dx-v2/cocos2dx/support/zip_support/unzip.cpp:1900: error: undefined reference to 'crc32'
Cocos2dx-v2/cocos2dx/support/zip_support/unzip.cpp:2064: error: undefined reference to 'inflateEnd'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-version.o):version.c:function Curl_version_init: error: undefined reference to 'zlibVersion'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-version.o):version.c:function Curl_version_init: error: undefined reference to 'zlibVersion'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-version.o):version.c:function curl_version: error: undefined reference to 'zlibVersion'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-version.o):version.c:function curl_version_info: error: undefined reference to 'zlibVersion'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function inflate_stream: error: undefined reference to 'inflate'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function inflate_stream: error: undefined reference to 'inflateInit2_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function inflate_stream: error: undefined reference to 'inflate'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function Curl_unencode_deflate_write: error: undefined reference to 'inflateInit_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(libcurl_la-content_encoding.o):content_encoding.c:function Curl_unencode_gzip_write: error: undefined reference to 'inflateInit2_'
Cocos2dx-v2/external/libwebsockets/android/./lib/armeabi-v7a/libwebsockets.a(extension-permessage-deflate.c.o):extension-permessage-deflate.c:function lws_extension_callback_pm_deflate: error: undefined reference to 'deflateEnd'
Cocos2dx-v2/external/libwebsockets/android/./lib/armeabi-v7a/libwebsockets.a(extension-permessage-deflate.c.o):extension-permessage-deflate.c:function lws_extension_callback_pm_deflate: error: undefined reference to 'deflateInit2_'
Cocos2dx-v2/external/libwebsockets/android/./lib/armeabi-v7a/libwebsockets.a(extension-permessage-deflate.c.o):extension-permessage-deflate.c:function lws_extension_callback_pm_deflate: error: undefined reference to 'deflate'
Cocos2dx-v2/external/libwebsockets/android/./lib/armeabi-v7a/libwebsockets.a(extension-permessage-deflate.c.o):extension-permessage-deflate.c:function lws_extension_callback_pm_deflate: error: undefined reference to 'deflateEnd'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(png.o):png.c:function png_reset_crc: error: undefined reference to 'crc32'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(png.o):png.c:function png_calculate_crc: error: undefined reference to 'crc32'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(png.o):png.c:function png_icc_set_sRGB: error: undefined reference to 'adler32'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(png.o):png.c:function png_icc_set_sRGB: error: undefined reference to 'adler32'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(png.o):png.c:function png_reset_zstream: error: undefined reference to 'inflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngrutil.o):pngrutil.c:function png_inflate_claim: error: undefined reference to 'inflateReset2'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngrutil.o):pngrutil.c:function png_decompress_chunk.constprop.5: error: undefined reference to 'inflateReset2'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngrutil.o):pngrutil.c:function png_decompress_chunk.constprop.5: error: undefined reference to 'inflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngwrite.o):pngwrite.c:function png_destroy_write_struct: error: undefined reference to 'deflateEnd'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngwutil.o):pngwutil.c:function png_deflate_claim: error: undefined reference to 'deflateInit2_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngwutil.o):pngwutil.c:function png_deflate_claim: error: undefined reference to 'deflateEnd'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngwutil.o):pngwutil.c:function png_deflate_claim: error: undefined reference to 'deflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngwutil.o):pngwutil.c:function png_text_compress.part.1: error: undefined reference to 'deflate'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libpng/libs/armeabi-v7a/libpng.a(pngwutil.o):pngwutil.c:function png_compress_IDAT: error: undefined reference to 'deflate'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogSetupDecode: error: undefined reference to 'inflateInit_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogPreDecode: error: undefined reference to 'inflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogDecode: error: undefined reference to 'inflateSync'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogSetupEncode: error: undefined reference to 'deflateInit_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogPreEncode: error: undefined reference to 'deflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogEncode: error: undefined reference to 'deflate'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_pixarlog.o):tif_pixarlog.c:function PixarLogVSetField: error: undefined reference to 'deflateParams'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_zip.o):tif_zip.c:function ZIPSetupDecode: error: undefined reference to 'inflateInit_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_zip.o):tif_zip.c:function ZIPPreDecode: error: undefined reference to 'inflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_zip.o):tif_zip.c:function ZIPDecode: error: undefined reference to 'inflateSync'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_zip.o):tif_zip.c:function ZIPSetupEncode: error: undefined reference to 'deflateInit_'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_zip.o):tif_zip.c:function ZIPPreEncode: error: undefined reference to 'deflateReset'
Cocos2dx-v2/cocos2dx/platform/third_party/android/prebuilt/libtiff/libs/armeabi-v7a/libtiff.a(tif_zip.o):tif_zip.c:function ZIPVSetField: error: undefined reference to 'deflateParams'
  collect2: error: ld returned 1 exit status

**Comment by yinjimmy** [comment]
Em, I cloned the repo and tested it. Build failed with android-ndk-r13b, plz use android-ndk-r10d.
Thanks for your time.

![image](https://user-images.githubusercontent.com/5056328/52651349-f825cb80-2f26-11e9-9db3-879f6d32cc13.png)

**Comment by daniaDlbani** [comment]
I thought that ndk r13b is necessary for the debug

**Comment by yinjimmy** [comment]
`git pull` and test, support compile with ndk-r14b now.

**Comment by yinjimmy** [comment]
https://discuss.cocos2d-x.org/t/cocos2dx-v2-2-6-migration-to-android-studio/45495/27?u=yinjimmy

one developer build success.

**Comment by yinjimmy** [comment]
fixed with https://github.com/c0i/cocos2d-x-v2/releases/tag/v1.0-beta
